name: semestr_job

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - ${MONGOEXPRESS_PORT}:${MONGOEXPRESS_PORT}
