import os
from dotenv import load_dotenv

load_dotenv()


MONGO_INITDB_ROOT_USERNAME = os.getenv("MONGO_INITDB_ROOT_USERNAME")
MONGO_INITDB_ROOT_PASSWORD = os.getenv("MONGO_INITDB_ROOT_PASSWORD")
ME_CONFIG_MONGODB_ADMINUSERNAME = os.getenv(
    "ME_CONFIG_MONGODB_ADMINUSERNAME"
)
ME_CONFIG_MONGODB_ADMINPASSWORD = os.getenv(
    "ME_CONFIG_MONGODB_ADMINPASSWORD"
)
ME_CONFIG_BASICAUTH_USERNAME = os.getenv("ME_CONFIG_BASICAUTH_USERNAME")
ME_CONFIG_BASICAUTH_PASSWORD = os.getenv("ME_CONFIG_BASICAUTH_PASSWORD")
ME_CONFIG_MONGODB_SERVER = os.getenv("ME_CONFIG_MONGODB_SERVER")
DOMAIN = os.getenv("DOMAIN")
MONGODB_PORT = os.getenv("MONGODB_PORT")
MONGOEXPRESS_PORT = os.getenv("MONGOEXPRESS_PORT")
TIMEZONE = os.getenv("TIMEZONE")
